version: "2"
services:
  react:
    build:
      context: ./frontend # Either a path to a directory containing a Dockerfile, or a url to a git repository.
    command: "npm start"
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
  express:
    build:
      context: ./backend
    command: "node index.js"
    volumes:
      - ./backend:/usr/app
      - usr/app/node_modules
    ports:
      - "3001:3001"
